import { FETCH_SKILLS, UPDATE_SKILL } from '../actions/skills/skillsActionTypes'

const getSkills = () => {
    const skills = [
      {id: 0,
       type: "ויזואלי",
       wasAchieved: true,
       description: "זיהויי דמויות וחפצים באמצעות המראה שלהם",
      },
      {id: 1,
       type: "תחושתי",
       wasAchieved: false,
       description: "זיהויי דמויות וחפצים באמצעות המראה שלהם",
      },
      {id: 2,
       type: "קוגנטיבי",
       wasAchieved: true,
       description: "זיהויי דמויות וחפצים באמצעות המראה שלהם",
      },
      {id: 3,
       type: "ווקאלי",
       wasAchieved: true,
       description: "זיהויי דמויות וחפצים באמצעות המראה שלהם",
      },
      {id: 4,
       type: "טקסטואלי",
       wasAchieved: false,
       description: "זיהויי דמויות וחפצים באמצעות המראה שלהם",
      },
      {id: 5,
        type: "קוגנטיבי",
       wasAchieved: false,
       description: "זיהויי דמויות וחפצים באמצעות המראה שלהם",
      },
      {id: 6,
        type: "תחושתי",
       wasAchieved: true,
       description: "זיהויי דמויות וחפצים באמצעות המראה שלהם",
      },
      {id: 7,
        type: "ויזואלי",
       wasAchieved: false,
       description: "זיהויי דמויות וחפצים באמצעות המראה שלהם",
      },
    ]
    return (skills);
  };
// const getSkills = () => {
//     const skills = [
//        {id: 1,
//         level: 1,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 2,
//         level: 1,
//         type: "עצמאות במטלות הבית",
//         status: {wasAchieved: false, emerging: false, unachieved: true},
//         description: "פונה לכיוון קול משחקי אנושי (למשל שריקה).",
//        },
//        {id: 3,
//         level: 1,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 4,
//         level: 1,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 5,
//         level: 1,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 6,
//         level: 1,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 7,
//         level: 1,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 8,
//         level: 1,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 9,
//         level: 1,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 10,
//         level: 1,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 11,
//         level: 1,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 13,
//         level: 1,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 14,
//         level: 1,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 15,
//         level: 1,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 16,
//         level: 1,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 17,
//         level: 1,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 18,
//         level: 1,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 19,
//         level: 1,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 20,
//         level: 1,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 21,
//         level: 1,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 22,
//         level: 1,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 23,
//         level: 1,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 24,
//         level: 1,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 25,
//         level: 1,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 26,
//         level: 1,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 27,
//         level: 1,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 28,
//         level: 1,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 29,
//         level: 1,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 30,
//         level: 1,
//         type: "כישורים חברתיים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 31,
//         level: 1,
//         type: "כישורים חברתיים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 32,
//         level: 1,
//         type: "כישורים חברתיים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 33,
//         level: 1,
//         type: "כישורים חברתיים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 34,
//         level: 1,
//         type: "כישורים חברתיים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 35,
//         level: 1,
//         type: "כישורים חברתיים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 36,
//         level: 1,
//         type: "כישורים חברתיים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 37,
//         level: 1,
//         type: "כישורים חברתיים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 38,
//         level: 1,
//         type: "כישורים חברתיים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 39,
//         level: 1,
//         type: "כישורים חברתיים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 40,
//         level: 1,
//         type: "חיקוי",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 41,
//         level: 1,
//         type: "חיקוי",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 42,
//         level: 1,
//         type: "חיקוי",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 43,
//         level: 1,
//         type: "חיקוי",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 44,
//         level: 1,
//         type: "משחק",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 45,
//         level: 1,
//         type: "משחק",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 46,
//         level: 1,
//         type: "משחק",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 47,
//         level: 1,
//         type: "משחק",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 48,
//         level: 1,
//         type: "משחק",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 49,
//         level: 1,
//         type: "משחק",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 50,
//         level: 1,
//         type: "משחק",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 51,
//         level: 1,
//         type: "משחק",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 52,
//         level: 1,
//         type: "התנהגות",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 53,
//         level: 1,
//         type: "התנהגות",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 54,
//         level: 1,
//         type: "התנהגות",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 55,
//         level: 1,
//         type: "התנהגות",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 56,
//         level: 1,
//         type: "התנהגות",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 57,
//         level: 1,
//         type: "עצמאות באכילה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 58,
//         level: 1,
//         type: "עצמאות באכילה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 59,
//         level: 1,
//         type: "עצמאות באכילה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 60,
//         level: 1,
//         type: "עצמאות באכילה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 61,
//         level: 1,
//         type: "עצמאות באכילה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 62,
//         level: 1,
//         type: "עצמאות באכילה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 63,
//         level: 1,
//         type: "עצמאות באכילה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 64,
//         level: 1,
//         type: "עצמאות באכילה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 65,
//         level: 1,
//         type: "עצמאות בלבוש",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 66,
//         level: 1,
//         type: "עצמאות בלבוש",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 67,
//         level: 1,
//         type: "עצמאות בהגיינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 68,
//         level: 1,
//         type: "עצמאות בהגיינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 69,
//         level: 1,
//         type: "עצמאות בהגיינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 70,
//         level: 1,
//         type: "עצמאות בהגיינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 71,
//         level: 1,
//         type: "עצמאות בהגיינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 72,
//         level: 1,
//         type: "עצמאות בהגיינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 73,
//         level: 1,
//         type: "עצמאות במטלות הבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 74,
//         level: 1,
//         type: "עצמאות במטלות הבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 75,
//         level: 1,
//         type: "מוטוריקה עדינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 76,
//         level: 1,
//         type: "מוטוריקה עדינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 77,
//         level: 1,
//         type: "מוטוריקה עדינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 78,
//         level: 1,
//         type: "מוטוריקה עדינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 79,
//         level: 1,
//         type: "מוטוריקה עדינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 80,
//         level: 1,
//         type: "מוטוריקה עדינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 81,
//         level: 1,
//         type: "מוטוריקה עדינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 82,
//         level: 1,
//         type: "מוטוריקה עדינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 83,
//         level: 1,
//         type: "מוטוריקה עדינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 84,
//         level: 1,
//         type: "מוטוריקה עדינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 85,
//         level: 1,
//         type: "מוטוריקה עדינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 86,
//         level: 1,
//         type: "מוטוריקה עדינה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 87,
//         level: 1,
//         type: "מוטוריקה גסה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 88,
//         level: 1,
//         type: "מוטוריקה גסה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 89,
//         level: 1,
//         type: "מוטוריקה גסה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 90,
//         level: 1,
//         type: "מוטוריקה גסה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 91,
//         level: 1,
//         type: "מוטוריקה גסה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 92,
//         level: 1,
//         type: "מוטוריקה גסה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 93,
//         level: 1,
//         type: "מוטוריקה גסה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 94,
//         level: 1,
//         type: "מוטוריקה גסה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 95,
//         level: 2,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 96,
//         level: 2,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 97,
//         level: 2,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 98,
//         level: 2,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 99,
//         level: 2,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 100,
//         level: 2,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 101,
//         level: 2,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 102,
//         level: 2,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 103,
//         level: 2,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 104,
//         level: 2,
//         type: "שפה רצפטיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 105,
//         level: 2,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 106,
//         level: 2,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 107,
//         level: 2,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 108,
//         level: 2,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 109,
//         level: 2,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 110,
//         level: 2,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 111,
//         level: 2,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 112,
//         level: 2,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 113,
//         level: 2,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 114,
//         level: 2,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 115,
//         level: 2,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 116,
//         level: 2,
//         type: "שפה אקספרסיבית",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 117,
//         level: 2,
//         type: "כישורים חברתיים עם מבוגרים או חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 118,
//         level: 2,
//         type: "כישורים חברתיים עם מבוגרים או חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 119,
//         level: 2,
//         type: "כישורים חברתיים עם מבוגרים או חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 120,
//         level: 2,
//         type: "כישורים חברתיים עם מבוגרים או חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 121,
//         level: 2,
//         type: "כישורים חברתיים עם מבוגרים או חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 122,
//         level: 2,
//         type: "כישורים חברתיים עם מבוגרים או חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 123,
//         level: 2,
//         type: "כישורים חברתיים עם מבוגרים או חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 124,
//         level: 2,
//         type: "כישורים חברתיים עם מבוגרים או חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 125,
//         level: 2,
//         type: "כישורים חברתיים עם מבוגרים או חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 126,
//         level: 2,
//         type: "כישורים חברתיים עם מבוגרים או חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 127,
//         level: 2,
//         type: "כישורים חברתיים עם חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 128,
//         level: 2,
//         type: "כישורים חברתיים עם חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 129,
//         level: 2,
//         type: "כישורים חברתיים עם חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 130,
//         level: 2,
//         type: "כישורים חברתיים עם חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 131,
//         level: 2,
//         type: "כישורים חברתיים עם חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 132,
//         level: 2,
//         type: "כישורים חברתיים עם חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 133,
//         level: 2,
//         type: "כישורים חברתיים עם חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 134,
//         level: 2,
//         type: "כישורים חברתיים עם חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 135,
//         level: 2,
//         type: "כישורים חברתיים עם חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 136,
//         level: 2,
//         type: "כישורים חברתיים עם חברים",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 137,
//         level: 2,
//         type: "קשב משותף",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 138,
//         level: 2,
//         type: "קשב משותף",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 139,
//         level: 2,
//         type: "קשב משותף",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 140,
//         level: 2,
//         type: "קשב משותף",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 141,
//         level: 2,
//         type: "קשב משותף",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 142,
//         level: 2,
//         type: "קשב משותף",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 143,
//         level: 2,
//         type: "קשב משותף",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 144,
//         level: 2,
//         type: "קשב משותף",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 145,
//         level: 2,
//         type: "חיקוי",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 146,
//         level: 2,
//         type: "חיקוי",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 147,
//         level: 2,
//         type: "חיקוי",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 148,
//         level: 2,
//         type: "חיקוי",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 149,
//         level: 2,
//         type: "חיקוי",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 150,
//         level: 2,
//         type: "חיקוי",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 151,
//         level: 2,
//         type: "חיקוי",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 152,
//         level: 2,
//         type: "חיקוי",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 153,
//         level: 2,
//         type: "חיקוי",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 154,
//         level: 2,
//         type: "קוגניציה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 155,
//         level: 2,
//         type: "קוגניציה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 156,
//         level: 2,
//         type: "קוגניציה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 157,
//         level: 2,
//         type: "קוגניציה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 158,
//         level: 2,
//         type: "קוגניציה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 159,
//         level: 2,
//         type: "קוגניציה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 160,
//         level: 2,
//         type: "קוגניציה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 161,
//         level: 2,
//         type: "קוגניציה",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//        {id: 162,
//         level: 2,
//         type: "משחק",
//         status: {wasAchieved: true, emerging: false, unachieved: false},
//         description: "פונה לכיוון קול על-ידי הפניית גוף למקור הקול.",
//        },
//     ]
//     return (skills);
//   };

const initialState = {
    allSkills: getSkills(),
}

const skillsReducer = (state = initialState, action) => {
    switch (action.type) {
        case FETCH_SKILLS:
            const newSkills = action.payload;
            const newState = { newSkills };
            return newState;
            break
        case UPDATE_SKILL:
            const skill = action.payload;
            const updatedSkills = state.allSkills;
            updatedSkills[skill.id].wasAchieved = skill.wasAchieved;
            const updatedState = { allSkills: updatedSkills };
            return updatedState;
            break
        default:
            return state;
    }
};

export default skillsReducer;